### ISSUE TITLE
feedback on project outline

### ISSUE THREAD

**Issue by dcmorse** [exclamationkate/liftoff-assignments#1]
Your vision of weaving together recipes, inventory, and grocery lists strikes me as both intricate and easy-to-communicate. You'll have interesting application-specific logic - for example, subtracting inventory from a recipe to generate a grocery list. In short, I like this idea a lot. 

While I love your feature list, it is also probably beyond the minimum you'll need to get a job. If you came to class with `user login` and `foods about to expire` C.R.U.D., and really any one of the other three features, I'm sure Koko would not think twice to send you for job interviews. I know that you've got a lot on your plate (food joke!), so consider how you could best trim it down. 

For example, while it'd be great to hit a food api, maybe it'd be easier to have a hardcoded list of recipies loaded from a text file, or stored in your database? I'm not trying to talk you out of the food API, instead I'm trying to brainstorm options. 

____

My other observation is that you've got Thymeleaf on your API list and not Angular. Is that a deliberate decision to avoid Angular, or an oversight?  Nowadays most apps are built with a JS framework on the front end (e.g. Angular) and a strongly typed language on the back end (e.g. Java). Server side views with templating languages like Thymeleaf will never be phased out entirely, but servers returning json to front-end frameworks like Angular will be dominant, more complex, and more powerful. 

Overall: good job. Assignment accepted. See you in 1.8 weeks.

**Comment by exclamationkate** [comment]
The hardcoded list is a great idea as a stepping stone to something bigger down the road and a good way to test out my site early on. I also did forget to throw Angular on that list, noted and added!
